# https://gohugo.io/content-management/menus/#params
main:
  - name: 홈
    url: /
    weight: -110
  - name: 소개
    url: about
    weight: -100    
  - name: 레이아웃 목록
    url: library
    weight: -90

button:
  - name: about
    url: durumi.io
    weight: -110
  - name: github
    url: https://github.com/team-durumi
    weight: -100