# https://gohugo.io/content-management/menus/#params
# identifier params for header scrolling
main:
  - name: 소개
    url:
    weight: -110
  - name: 냉전평화연구센터
    url: /about
    weight: 1
    parent: 소개
  - name: 동아시아연구소
    url: http://ieas21.or.kr/
    weight: 2
    parent: 소개
  - name: 성과
    url: 
    weight: -100
  - name: 학술회의
    url: /categories/meetings
    weight: 1
    parent: 성과
  - name: 사업
    url: /categories/projects
    weight: 2
    parent: 성과 
  - name: 논문
    url: /categories/articles
    weight: 3
    parent: 성과
  - name: 책
    url: /categories/books
    weight: 4
    parent: 성과                    
  - name: 영상 탐색
    url: 
    weight: -90
  - name: 탐색
    url: /items
    weight: 1
    parent: 영상 탐색
  - name: 검색
    url: https://catalog.facwa.kr/
    weight: 2
    parent: 영상 탐색
  - name: 컬렉션
    url: 
    weight: -80
  - name: 태그
    url: /tags/
    weight: 6
    parent: 컬렉션     
  - name: 생산자
    url: /creators/
    weight: 2
    parent: 컬렉션     
  - name: 주제
    url: /subjects/
    weight: 3
    parent: 컬렉션       
  - name: 출처
    url: /sources/
    weight: 4
    parent: 컬렉션     
  - name: 장소
    url: /venues/
    parent: 컬렉션
    weight: 5
  - name: 콘텐츠
    url: 
    weight: -70
  - name: 쇼츠
    url: /shorts
    weight: 1
    parent: 콘텐츠
button:
- name: 검색
  url: https://catalog.facwa.kr/
  weight: -90