hugoVersion:
  extended: true
  min: "0.55.0"

imports:
- path: github.com/team-durumi/hugo-marketing
- path: github.com/team-durumi/hugo-search-fuse-js-aa
replacements: "github.com/team-durumi/hugo-marketing -> ../.."
